# Generated by Django 6.0.3 on 2026-05-31 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioBarbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_entrada', models.TimeField(default='08:00')),
                ('hora_salida', models.TimeField(default='20:00')),
                ('inicio_almuerzo', models.TimeField(blank=True, null=True)),
                ('fin_almuerzo', models.TimeField(blank=True, null=True)),
                ('dia_descanso', models.BooleanField(default=False)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='gestion.barbero')),
            ],
            options={
                'ordering': ['dia_semana'],
                'unique_together': {('barbero', 'dia_semana')},
            },
        ),
        migrations.CreateModel(
            name='HorarioSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_apertura', models.TimeField(default='08:00')),
                ('hora_cierre', models.TimeField(default='20:00')),
                ('cerrado', models.BooleanField(default=False)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='gestion.sede')),
            ],
            options={
                'ordering': ['dia_semana'],
                'unique_together': {('sede', 'dia_semana')},
            },
        ),
    ]
