# Generated by Django 6.0.1 on 2026-06-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_servicio_cita_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='hora_llegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Verificación'), ('Confirmada', 'Confirmada (Esperando Cliente)'), ('En_Atencion', 'Cliente en Barbería'), ('Completada', 'Servicio Finalizado'), ('No_Asistio', 'No Asistió'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
    ]
