# Generated by Django 6.0.1 on 2026-06-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_cita_hora_llegada_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cliente_nombre',
            field=models.CharField(default='Cliente', max_length=100),
        ),
    ]
