# Generated by Django 6.0.1 on 2026-06-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_cita_cliente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='intentos_verificacion',
            field=models.IntegerField(default=0),
        ),
    ]
