# Generated by Django 6.0.1 on 2026-06-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_cita_intentos_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
