# Generated by Django 6.0.1 on 2026-01-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidad')),
                ('foto', models.ImageField(upload_to='barberos/', verbose_name='Foto de Perfil')),
            ],
            options={
                'verbose_name': 'Barbero',
                'verbose_name_plural': 'Nuestros Barberos',
            },
        ),
    ]
